### ISSUE TITLE
무한루프

### ISSUE THREAD

**Issue by Jinseok2419342** [Jinseok2419342/Conan#15]
# 죽어야만 나갈 수 있는 버그 
## (뭐야, 살려줘요)

https://github.com/user-attachments/assets/c8fa52e3-c34e-4c70-ae9c-7de9c7f11750

**Comment by suhan1029** [comment]
이거 저도 테스트하다가 가끔 이랬는데, 양 옆에 영역을 지정하고 그 영역에서 공이 3초이상 있으면 공을 가운데로 강제로 텔포시키는 기능을 넣어야겠네요

**Comment by eunsg1** [comment]
양 옆에다 투명 블록 만들어버리죠?
