### ISSUE TITLE
공이 뭔가 느려진거 같은데 기분탓인가요? 

### ISSUE THREAD

**Issue by Jinseok2419342** [Jinseok2419342/Conan#33]
제 커밋 확인해봐도 관련해서 바꾼게 없는데 공 속도가 뭔가 느려진거 같은데 기분탓인가요?

내 눈이 진화했나

**Comment by eunsg1** [comment]
배경 추가했더니 렉걸리는 것 같아요
이럴 수가

**Comment by eunsg1** [comment]
프레임마다 사진 불러오기 해서 렉이 심하게 걸리나 봐요
