### ISSUE TITLE
버그들

### ISSUE THREAD

**Issue by eunsg1** [Jinseok2419342/Conan#55]
금방 수정할 수 있는 것
- (해결) 양쪽 벽에 공이 박혀서 비비는 현상
- 게임 클리어 시 랭크와 시간 표시 안됨
- 스테이지 클리어 시 시간이 초기화됨(마지막 스테이지 클리어만 놓고 랭크가 정해져버림)
- (해결) 게임 클리어 시 맵과 시간, 패들, 파괴 불가능 벽돌 등 여러가지 초기화 안됨

**Comment by Jinseok2419342** [comment]
안돼..... exe 파일 만들었는데 ㅠㅠ

**Comment by eunsg1** [comment]
![우는 이모](https://github.com/user-attachments/assets/8820d9a8-84e6-4c86-b10c-beee211a93e9)

**Comment by eunsg1** [comment]
급한 불은 다 끈 것 같아요!
